amqp:
    connection:
        consumer:
            host        : ["localhost"]
            port        : 5672
            login       : admin
            password    : admin
            vhost       : /

    channel:
        consumer:
            connection  : consumer

    exchange:
        main_exchange:
            channel: consumer
            name:
                name: main_exchange
                type: constant
            dependencies:
                exchange:
                    - dlx_exchange
            type: AMQP_EX_TYPE_TOPIC

        dlx_exchange:
            channel: consumer
            name:
                name: dlx_exchange
                type: constant
            type: AMQP_EX_TYPE_TOPIC

    queue:
        main_queue:
            channel: consumer
            name:
                name: main_queue
                type: constant
            arguments:
                dl_exchange: dlx_exchange
                dl_routingKey: test
            flags: [AMQP_DURABLE]
            bindings:
                -
                    exchange: main_exchange
                    routingKey: "#"
            dependencies:
                queue:
                    - dlx_queue

        dlx_queue:
            channel: consumer
            name:
                name: dlx_queue
                type: constant
            bindings:
                -
                    exchange: dlx_exchange
                    routingKey: "#"
            flags: [AMQP_DURABLE]
